export enum MULTI_LEVEL_CARD_TYPE  {
    FARM = 'farm',
    MINE = 'mine',
    MARKET = 'market',
    BANK = 'bank',
    BARRACK = 'barrack',
    AIR_FORCE = 'air_force',
    TECH = 'tech',
    HOSPITAL = 'hospital',
    HOUSE = 'house',
    ARMY = 'army',
}

export enum UNIQUE_LEVEL_CARD_TYPE {
    PRESIDENT = 'president', 
    DICTATOR = 'dictator', 
    EMBASSY = 'embassy', 
    HBOMB = 'hbomb', 
    MISSILE = 'missile', 
}


export enum CARD_CATEGORY {
    BASIC = "basic",
    ECONOMIC = "economic",
    MILITARY = "military",
    PROGRESS = "progress",
    UTILITY = "utility",
    DIPLOMATIC = "diplomatic",
    LEADERSHIP = "leadership", 
}

export const CARD_CATEGORY_TO_CARD_TYPE_MAP = {
    [CARD_CATEGORY.BASIC]: [MULTI_LEVEL_CARD_TYPE.FARM, MULTI_LEVEL_CARD_TYPE.MINE],
    [CARD_CATEGORY.ECONOMIC ]: [MULTI_LEVEL_CARD_TYPE.MARKET, MULTI_LEVEL_CARD_TYPE.BANK],
    [CARD_CATEGORY.MILITARY]: [MULTI_LEVEL_CARD_TYPE.BARRACK, MULTI_LEVEL_CARD_TYPE.AIR_FORCE],
    [CARD_CATEGORY.PROGRESS]: [MULTI_LEVEL_CARD_TYPE.TECH, MULTI_LEVEL_CARD_TYPE.HOSPITAL, MULTI_LEVEL_CARD_TYPE.HOUSE],
    [CARD_CATEGORY.UTILITY]: [MULTI_LEVEL_CARD_TYPE.ARMY, UNIQUE_LEVEL_CARD_TYPE.MISSILE, UNIQUE_LEVEL_CARD_TYPE.HBOMB],
    [CARD_CATEGORY.DIPLOMATIC]: [UNIQUE_LEVEL_CARD_TYPE.EMBASSY],
    [CARD_CATEGORY.LEADERSHIP]: [UNIQUE_LEVEL_CARD_TYPE.PRESIDENT, UNIQUE_LEVEL_CARD_TYPE.DICTATOR] 
}

export enum CARD_LEVEL {
    UNIQUE = 'unique',
    LVL_1 = 'lvl_1',
    LVL_2 = 'lvl_2',
    LVL_3 = 'lvl_3',
}
